# Generated by Django 4.2.2 on 2023-06-13 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.CharField(choices=[('10', '10'), ('11', '11'), ('9', '9'), ('12', '12')], default='10', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='related_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.course'),
        ),
    ]
