# Generated by Django 4.2.2 on 2023-06-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_name_alter_student_std_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.CharField(choices=[('9', '9'), ('10', '10'), ('12', '12'), ('11', '11')], default='10', max_length=50),
        ),
    ]
