# Generated by Django 4.2.2 on 2023-06-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.CharField(choices=[('12', '12'), ('10', '10'), ('11', '11'), ('9', '9')], default='10', max_length=50),
        ),
    ]
