# Generated by Django 4.2.2 on 2023-06-15 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_course_name_alter_student_std'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='Unique course name',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='related_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='r_course', to='app.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.CharField(choices=[('12', '12'), ('10', '10'), ('9', '9'), ('11', '11')], default='10', max_length=50),
        ),
    ]
