# Generated by Django 4.2.2 on 2023-06-16 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_course_unique_course_name_alter_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='Unique identity',
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='related_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.CharField(choices=[('9', '9'), ('12', '12'), ('11', '11'), ('10', '10')], default='10', max_length=50),
        ),
    ]
