# Generated by Django 4.2.2 on 2023-06-16 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_student_unique_identity_subject_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.CharField(choices=[('11', '11'), ('10', '10'), ('12', '12'), ('9', '9')], default='10', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(default='NOTHING', on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('roll_no', 'std'), name='Unique identity'),
        ),
    ]
