# Generated by Django 4.2.2 on 2023-06-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_student_std_alter_subject_course_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='Unique identity',
        ),
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.CharField(choices=[('10', '10'), ('12', '12'), ('9', '9'), ('11', '11')], default='10', max_length=50),
        ),
    ]
