# Generated by Django 4.2.2 on 2023-06-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_student_std_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.CharField(choices=[('9', '9'), ('12', '12'), ('10', '10'), ('11', '11')], default='10', max_length=50),
        ),
    ]
