# Generated by Django 4.2.2 on 2023-06-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_student_std'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.CharField(choices=[('9', '9'), ('12', '12'), ('11', '11'), ('10', '10')], default='10', max_length=50),
        ),
    ]
