# Generated by Django 4.2.2 on 2023-06-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_student_unique_together_alter_student_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.CharField(choices=[('10', '10'), ('11', '11'), ('9', '9'), ('12', '12')], default='10', max_length=50),
        ),
    ]
