# Generated by Django 4.2.2 on 2023-06-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_course_name_alter_student_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.CharField(choices=[('10', '10'), ('9', '9'), ('11', '11'), ('12', '12')], default='10', max_length=50),
        ),
    ]
