# Generated by Django 4.2.1 on 2023-06-22 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_student_std'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'All Students'},
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.CharField(choices=[('9', '9'), ('12', '12'), ('10', '10'), ('11', '11')], default='10', max_length=50),
        ),
    ]
